### ISSUE TITLE
Clean the code 

### ISSUE THREAD

**Issue by M-ds** [EvilAngel94/asciidoc-book-template#3]
**Description**
Conduct a really strict search on the code. Is all the code really named correctly, are all the functions logic.

**TODO**
- [ ] Make sure the template can be modified easily.
- [ ] Refactor the CSS file and organize this better.
- [ ] Refactor the README.md if the functionallity is not explained correctly.
- [ ] Make sure a simple wiki is created to explain this more.
